### PR TITLE
added inputRest to FileInput component

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
added inputRest to FileInput component

### CODE REVIEW

**Comment by endigo9740** [comment]
@Mahmoud-zino this is one of those areas I wish we had a React pro to ask, and perhaps I'm crazy, but I was thinking React had a manner to replicate restProps. I cannot for the life of me recall what it was, but I don't think it involved dropping values into an object like this.

Let's go ahead and do some additional due diligence here and look around and see if we can find something like this. Perhaps even see if we can reach out in a React community and ask.

**Comment by Mahmoud-zino** [comment]
@endigo9740 you are totally correct on that, I have found a better approach and updated the PR. let me know what you think about it.

**Comment by endigo9740** [comment]
Very nice find @Mahmoud-zino, so we have control over the naming of `extraProp` or is that a reserved term? I figure we might go with `restProps` for now for familiarity. Especially if this is something that's not publicly visible.

Outside of that everything else looks great and I'll look forward to merging soon.

**Comment by Mahmoud-zino** [comment]
@endigo9740 I added the `extraProp` just to clarify that we can use whatever props we need in combination with the rest props. feel free to change it as you want :+1:

**Pull request merged**
